export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_SLIDER = 'GET_SLIDER';
export const POST_FAVORITES = 'GET_FAVORITES';
export const REMOVE_FAVORITES = 'REMOVE_FAVORITES';
export const GET_FAVORITES = "GET_FAVORITES";